### ISSUE TITLE
Chrome logs "Intervention" error when dragging with touch

### ISSUE THREAD

**Issue by gbenthomas** [angular-split/angular-split#135]
Repro Steps:

-Use simple example  (https://bertrandg.github.io/angular-split/#/examples/simple-split)
-Use responsive emulator in Chrome and drag with emulated touch (or use device with touch)
-Chrome logs the following error in the console: "[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080"

**Comment by teetl6** [comment]
Some solutions for that? Having the same problem with nested split.

**Comment by MRROOX** [comment]
I have the same problem... any solution?

**Comment by helder-a-reis** [comment]
I had the same problem. After reading this explanation https://developers.google.com/web/updates/2017/01/scrolling-intervention, where it states "We've found that a large majority of impacted pages are fixed relatively easily by applying the touch-action CSS property whenever possible.",  I was able to suppress the error by adding
as-split {
    touch-action: pan-y;
}
to my CSS (for direction="vertical", you might have to adjust to your case).
