### ISSUE TITLE
Transition not working well with pixel unit.

### ISSUE THREAD

**Issue by Martingb93** [angular-split/angular-split#156]
I tried using pixels instead of percent for unit and the result with transition was not expanding smoothly as expected to be like the percent does.

Like in my example i try to expand the mid panel area with wildCard('*') ,the right panel area goes invisible instantly.
link ->  https://stackblitz.com/edit/angular-jjuqtr?file=src%2Fapp%2Fapp.component.html

In the end i found it working when i changed the mid panel area css  `<as-split-area size='*'>` flex when expanded to  `flex: 1 1 100%` instead of  `flex: 0 0 100%;`.

**Comment by bertrandg** [comment]
Hi,
You're right, thanks to report with demo.
I'm playing with it currently, will see what i can do and test your solution:
https://stackblitz.com/edit/angular-sjtwn5?file=src%2Fapp%2Fapp.component.ts
