### ISSUE TITLE
change default values 

### ISSUE THREAD

**Issue by Shemesh** [angular-split/angular-split#166]
@bertrandg hi,
in v3 the unit property default value is 'percent', right?
let's say i have 33 spliters in my app, i want them all to be unit='pixel'...
i do not want to set it on each instance, but set it globally per the whole application.

how?

**Comment by bertrandg** [comment]
Yes that's in my improvement list to add a global service to change default values.

**Comment by beeman** [comment]
I would suggest we add a configuration option to the `forRoot` method that allows to set the default.

Happy to accept PR's that add this.

**Comment by beeman** [comment]
This is now available in `angular-split@13.1.0`.
