### ISSUE TITLE
Incorrect @Input size typing when strictTemplates is enabled

### ISSUE THREAD

**Issue by KeithGillette** [angular-split/angular-split#220]
**Describe the bug**
AOT compilation build under Angular 9 with `angularCompilerOptions.strictTemplates: true` in `tsconfig.app.json` generates a `error TS2322: Type 'string' is not assignable to type 'number'` when binding `<as-split-area [size]="'*'">`, as the `@Input size` is typed as `number | null` in[ the source code](https://github.com/bertrandg/angular-split/blob/master/projects/angular-split/src/lib/directive/splitArea.directive.ts#L28), though the [documentation](https://bertrandg.github.io/angular-split/#/documentation) clearly states it can also be bound to `'*'` in pixel mode.

**Comment by Maximaximum** [comment]
I'm having exactly the same issue. This is clearly a bug, so I hope it will be fixed

**Comment by Maximaximum** [comment]
Hm, I wonder if this project is still maintained? 😢

**Comment by literalpie** [comment]
As a workaround, you can use `$any` in the template

```
	<as-split-area [size]="$any('*')">hello</as-split-area>
```

**Comment by ahnpnl** [comment]
Hi, any updates on this issue ?

**Comment by beeman** [comment]
> Hi, any updates on this issue ?

For now the recommend way to handle this is using `$any()` as mentioned [here](https://github.com/angular-split/angular-split/issues/220#issuecomment-645945845). 

Once v5 is released, built using Angular 10, I will consider fixing this.

**Comment by beeman** [comment]
> @beeman — Wasn't this incorrect typing already resolved in [your `ngx-split` fork](https://github.com/beeman/ngx-split)? We've been using that fork without the `$any('*')` work-around in our Angular 10 project. I see now that [`ngx-split` is deprecated](https://github.com/beeman/ngx-split/issues/10) and `angular-split` being actively maintained again.

Correct, I solved it there so I know what's the fix.

I'm deprecated my fork because the original author decided to hand over maintainence of this library.

Just didn't get to merging back my fixes.

**Comment by KeithGillette** [comment]
Any timeline for merging the fix for this issue from `ngx-split`, @beeman?

We've been holding off on switching back from `ngx-split` to `angular-split` until this issue is closed, but now `ngx-split` throws a fatal error at runtime under `angular@11.1.0`:
```
core.js:6156 ERROR Error: Uncaught (in promise): Error: ASSERTION ERROR: Expecting flags [Expected=> number === boolean <=Actual]
Error: ASSERTION ERROR: Expecting flags [Expected=> number === boolean <=Actual]
```

**Comment by beeman** [comment]
@KeithGillette can't really give a timeline at this point, sorry. Simply too busy with other things.

I think the workaround using `$any('*')` is relatively simple, so you might consider that.

**Comment by lf-novelt** [comment]
thanks for the workaround.
However I wonder if this is symply a typing issue, or an actual issue with the code, as the project is in TypeScript, so the typing are generated from the actual code, and the code really expects the `size` Input to be a Number as seen here
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/projects/angular-split/src/lib/directive/split-area.directive.ts#L23

**Comment by beeman** [comment]
Hey @lf-novelt , if you check #289 you can see where it's set. Once I finish that PR it will work without the workaround.
