### ISSUE TITLE
Splitter bar does not work if height is not an explicit value

### ISSUE THREAD

**Issue by russfleming** [angular-split/angular-split#224]
In trying out the various examples, it seems that if the height attribute of the split-example CSS class is not set to an explicit value (e.g. 500px, etc.) but set to 'auto' or 100%, the divider bar is not displayed or is just a grey rectangle and not movable.

The result of this is that the height of the div containing the split panels must be explicitly given and not allowed to fill in the available space, such as when in an element of a flex box.

What I'm trying to achieve is a page that is responsive and has a header and footer of fixed height and the resizable middle area contain a set of divs that angular-split moves back and forth.  I'm doing this with a column flex box for these 3 areas (header, resizable middle and footer).

I'm hoping that I've missed something and this is possible. Thanks!

**Comment by stumanov** [comment]
> In trying out the various examples, it seems that if the height attribute of the split-example CSS class is not set to an explicit value (e.g. 500px, etc.) but set to 'auto' or 100%, the divider bar is not displayed or is just a grey rectangle and not movable.
> 
> The result of this is that the height of the div containing the split panels must be explicitly given and not allowed to fill in the available space, such as when in an element of a flex box.
> 
> What I'm trying to achieve is a page that is responsive and has a header and footer of fixed height and the resizable middle area contain a set of divs that angular-split moves back and forth. I'm doing this with a column flex box for these 3 areas (header, resizable middle and footer).
> 
> I'm hoping that I've missed something and this is possible. Thanks!

Try to set **position: fixed** of the container that hosts splitter. In my case it has worked.

**Comment by beeman** [comment]
Hey @russfleming, thanks for creating the issue.

Could you provide a repro that shows what you want to achieve, and what goes wrong?

Please use this as a starting point https://stackblitz.com/fork/angular-split .

**Comment by IgnacioHR** [comment]
I added a style on the page like this:

```
.as-split-gutter {
	height: revert !important;
}
```
I'm sorry, I'm not fluent in creating repro :( Hope this is of help

**Comment by IgnacioHR** [comment]
While working on another issue, I'm having this issue too.

Here is a small demo to show the problem. The gutter does not appear. When I set the attribute gutterSize="5" I get an error `Type 'string' is not assignable to type 'number'`.

https://stackblitz.com/edit/angular-ivy-fvjc72?file=src/app/dialog/dialog.component.html

**Comment by beeman** [comment]
> While working on another issue, I'm having this issue too.
> 
> Here is a small demo to show the problem. The gutter does not appear. When I set the attribute gutterSize="5" I get an error `Type 'string' is not assignable to type 'number'`.
> 
> [stackblitz.com/edit/angular-ivy-fvjc72?file=src/app/dialog/dialog.component.html](https://stackblitz.com/edit/angular-ivy-fvjc72?file=src/app/dialog/dialog.component.html)

Hey @IgnacioHR - this is because of strict type checking, and works as expected. When you use `gutterSize="5"` it will be interpreted as a string. The proper way to do this is to evaluate the value, like so: `[gutterSize]="5"`. That way Angular knows it's a number.

**Comment by IgnacioHR** [comment]
Thanks!

Well, I've added [gutterSize]="5" and no gutter is shown

**Comment by beeman** [comment]
> Thanks!
> 
> Well, I've added [gutterSize]="5" and no gutter is shown

You also need to provide an explicit height, like so:

https://stackblitz.com/edit/angular-ivy-jkxbzj?file=src%2Fapp%2Fapp.component.html

This issue exists because the splitter does not work if there is not explicit height. You might be able to work around it as per [this suggestion](https://github.com/angular-split/angular-split/issues/224#issuecomment-646524472) but I have not tried that.

**Comment by IgnacioHR** [comment]
I created a working solution here: https://stackblitz.com/edit/angular-ivy-fvjc72?file=src/app/app.component.ts The solution requires two things:

Add a style like this:
```
.as-split-gutter {
	height: revert !important;
}
```

At the component level, it is required to add 
```
encapsulation: ViewEncapsulation.None
```

In the component declaration ... something like this:

```
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  encapsulation: ViewEncapsulation.None
})
```

Now the gutter appears without having to explicitly indicate the height

**Comment by abhimodgi** [comment]
I am facing same issue we need to provide height for parent div by default otherwise it is not working. Even i have added min-height still it is not working.

**Comment by beeman** [comment]
> I am facing same issue we need to provide height for parent div by default otherwise it is not working. Even i have added min-height still it is not working.

Can you try one of the suggestions above? If that doesn't work, a repro would be helpful! :)

**Comment by beeman** [comment]
If someone still has this problem, please create a new issue with a repro on StackBlitz.
