### ISSUE TITLE
LOOKING FOR A MAINTAINER

### ISSUE THREAD

**Issue by bertrandg** [angular-split/angular-split#237]
Hello,

I didn't come there since long time and have no time to work on it, there's many PR/issues/bug reports let opened without answer, sorry for that.

If someone wants to maintain it and take the lead, i'm totally open to it, please reply there.

**Comment by ideapad** [comment]
@beeman

**Comment by beeman** [comment]
@bertrandg thanks a lot for considering. I would love to take over maintenance so I don't have to work on a separate fork 🙏

**Comment by bertrandg** [comment]
@beeman Awesome, I've seen your fork and was considering deprecating this lib and link your fork but make you maintainer is a better options!

Never did this before, I've just send you an access invitation.
Tell me if something more is needed 👍

**Comment by beeman** [comment]
I totally agree it's the better option, less fragmentation in the ecosystem is always good!

I think the other thing I need is access to npm so I can publish new releases:

`npm owner add beeman angular-split`

**Comment by bertrandg** [comment]
@beeman it should be good for npm ownership ;)

**Comment by beeman** [comment]
All looking good @bertrandg, thanks a lot!

**Comment by bertrandg** [comment]
Thanks to you 👍

**Comment by ideapad** [comment]
@bertrandg I also would love to take participation in maintenance as I am actively using your lib in my project

**Comment by beeman** [comment]
@ideapad it would be great to have more people working on this! It's probably good if we could coordinate efforts. 

Feel free to join [this channel](https://discord.gg/ACQnXnC) on Discord so we can chat about it :)

**Comment by beeman** [comment]
@bertrandg could you consider increasing my permissions so I can adjust things like branch protection?

**Comment by bertrandg** [comment]
Any idea how to do this?

**Comment by beeman** [comment]
@bertrandg I thought this could be done through the Manage Access panel, but it seems like it's limited to to organizations nowadays.

I've created the organization `angular-split`, and made you owner. With that you should be able to transfer ownership to the org. Hope that works for you.

**Comment by bertrandg** [comment]
@beeman Yes, I've just did it! 👍 
But website will need a fix: 
https://bertrandg.github.io/angular-split/ > 404
https://angular-split.github.io/angular-split/ > fail to load ressources, need new build with correct url

**Comment by beeman** [comment]
@bertrandg you're the best!  🎉

I'll look at rebuilding the sites properly, I got some ideas on how we can do that.

**Comment by beeman** [comment]
The website is now published here https://angular-split.github.io/. I'm going to update the references.

@bertrandg thanks a lot for collaborating on this, it really serves the community that we don't have fragmentation! 🎉

Closing this issue as it's is now resolved :)
