### ISSUE TITLE
ROADMAP: Plans for angular-split v4 and beyond

### ISSUE THREAD

**Issue by beeman** [angular-split/angular-split#240]
This issue tracks the plans for angular-split v4 and beyond.

### v4 is released: [angular-split@4.0.0](https://www.npmjs.com/package/angular-split/v/4.0.0) 🎉

✅ The goal for this release was to publish a new version that works with recent Angular versions.

### v5

The goal for this release is to improve the DX for working on this project.

- Migrate to Nx Workspace 
- Merge various demo apps into one single demo app 
- Refactor app so it uses modern Angular best practices (lazy load all the things, more modules, etc)

### Next

Functionality that is considered for feature releases:
- Any items that are listed in the [v6 milestone](https://github.com/angular-split/angular-split/milestone/1).

Feel free to add a comment if I missed something! 🙏

**Comment by beeman** [comment]
@ideapad if I recall correctly, you filed an issue for support on v8. Can you verify if `angular-split@4.0.0-beta.0` works on your Angular v8 app?

**Comment by ideapad** [comment]
> @ideapad if I recall correctly, you filed an issue for support on v8. Can you verify if `angular-split@4.0.0-beta.0` works on your Angular v8 app?

@beeman have checked on v.8.2.0 - no issues, works great

**Comment by beeman** [comment]
@ideapad awesome, thanks for testing!
