### ISSUE TITLE
minSize doesn't work

### ISSUE THREAD

**Issue by yevgeniy-belov** [angular-split/angular-split#255]
minSize doesn't work when there are more than two split areas.

Versions: 3.0.3 and 4.0.0
Example: https://stackblitz.com/edit/angular-uacvff

**Comment by beeman** [comment]
Hey @cssberries, thanks for filing this issue.

It looks like it's not particularly the number of areas, in this example it seems to work as expected:

https://stackblitz.com/edit/angular-split-demo-guggjn?file=src%2Fapp%2Fapp.component.html

Not that I set a `size` and `minSize` for all of the columns. Also, please make sure to use the latest 4.x version, the 3.x version are no longer supported.

Does this help you fix your issue?

**Comment by cssberries** [comment]
Hi beeman,

The first section can be actually squeezed to zero.

**Comment by beeman** [comment]
You're right, I see it now. I'm going to see if I can fix it.

**Comment by gorshkov-leonid** [comment]
Hello, @beeman, are you going to release new version with this fix in in the near future and when?
