### ISSUE TITLE
Gutter appears multiple times and breaks UI

### ISSUE THREAD

**Issue by IgnacioHR** [angular-split/angular-split#258]
**Describe the bug**

We are using angular-split inside a mat-step. Two of the steps looks similar and include an angular-split component.

On the initial step, everything looks OK (see screen capture)
On the following step, that is similar composition, the UI shows 5 gutter (looking at the source code in the browser) and the UI is totally broken.

**To Reproduce**

I'm not familiar with Stabilitz. Will try to create one and get back here.

**Comment by IgnacioHR** [comment]
Deleted because I can't create a demo for this. Will investigate further.

**Comment by beeman** [comment]
Ok, please re-open when you have a reproduction 👍
