### ISSUE TITLE
Not working on RTL

### ISSUE THREAD

**Issue by amirhaghajani** [angular-split/angular-split#270]
When parent is Right to Left, does not work right. When you pull the separator to the right, it does the opposite

**Comment by OhadC** [comment]
Did you try to use the "dir" property? https://angular-split.github.io/documentation

**Comment by beeman** [comment]
Hi @amirhaghajani . Thanks for creating this issue - a repro in StackBlitz would be appreciated. It should be asking for that in the issue template.

**Comment by beeman** [comment]
Please provide a StackBlitz repro.
