### ISSUE TITLE
is this alive??

### ISSUE THREAD

**Issue by Shemesh** [angular-split/angular-split#272]
@beeman is this project still alive?
any plans to merge pull requests?
any plans for new release?

**Comment by beeman** [comment]
> @beeman is this project still alive?
> any plans to merge pull requests?
> any plans for new release?

Yes :)

**Comment by Shemesh** [comment]
@beeman great to hear it is alive.
there are few pr waiting your handling, including my own new expand\collapse feature.
we are eagerly waiting for it to be published to npm.
can you estimate when it will be done?

**Comment by beeman** [comment]
Hey @Shemesh , can you please rebase your branch and create a new PR agains the `main` branch? 

I'm about to create a new release and want to add your expand/collapse into it.

Thanks!
