### ISSUE TITLE
dragEnd event not sent when single-clicking gutter

### ISSUE THREAD

**Issue by pweissenbacher** [angular-split/angular-split#283]
**Describe the bug**
Package version: 4.0.0
When dragging the gutter, the events "dragStart/dragEnd" are working fine.
But when soley clicking the gutter, the `dragStart` event is fired, but the `dragEnd` event is not.

**To Reproduce**
Look at the small Stackblitz example (dragging not updating, but events fired as described)
[StackBlitz Dev Mode](https://stackblitz.com/edit/angular-ivy-s3z3pt?file=src/app/app.component.html)
[StackBlitz App Mode](https://angular-ivy-s3z3pt.stackblitz.io)

**Comment by nomeaning777** [comment]
In the current implementation, the component fires `dragStart` when a mouse button is pressed.
However, it fires `dragEnd` only when the mouse cursor is moved and the button is released. 
If mouse cursor is not moved, it emits `gutterClick`/`gutterDblClick`.
https://github.com/angular-split/angular-split/blob/main/projects/angular-split/src/lib/component/split.component.ts#L709

I think it is better to fire `dragStart` event only when a mouse button is pressed and the cursor is moved.
I will be happy to create a PR if this breaking change is acceptable.

**Comment by beeman** [comment]
@nomeaning777 I'm definitely interested in a PR that adds support for this (or maybe, fixes the bug that `dragStart` gets emitted when nothing gets dragged). 

It would be awesome if it could be implemented with minimal amount of code changes, and add some cypress tests that prove the behavior.

I think we can publish that in a major version, maybe it can go into v5.

**Comment by beeman** [comment]
This fix is released in version 5.0.0 thanks to @nomeaning777 🎉

https://stackblitz.com/edit/angular-ivy-xhc5bj?file=src/app/app.component.html
