### ISSUE TITLE
Documentation wrong on minSize and maxSize

### ISSUE THREAD

**Issue by rsivan** [angular-split/angular-split#285]
**Describe the bug**
**Documentation says** (https://angular-split.github.io/documentation):
"Maximum pixel or percent size, can't be bigger than provided size."
**Should be**:
Maximum pixel or percent size, can't be smaller than provided size.

Similar but opposite for minSize.

version v11.0.2

**To Reproduce**
Just open the documentation page.

**Comment by beeman** [comment]
Hey @rsivan, thanks for creating this issue!

I just updated this part of the docs, I hope it's clearer now :)

![image](https://user-images.githubusercontent.com/36491/102595216-3ec94b80-40e5-11eb-99cb-64e7ce663754.png)
