### ISSUE TITLE
Npm links broken

### ISSUE THREAD

**Issue by rsivan** [angular-split/angular-split#286]
**Describe the bug**
The following npm link at https://www.npmjs.com/package/angular-split is broken:

https://bertrandg.github.io/angular-split/

version (at npm): 4.0.0

**To Reproduce**
Look at npm link above

**Comment by beeman** [comment]
Hey @rsivan, thanks for the heads-up.

This is now fixed since release 5.0.0 got published!

![image](https://user-images.githubusercontent.com/36491/102593660-25bf9b00-40e3-11eb-9947-1424e952e73d.png)
