### ISSUE TITLE
 I need Single vertical scroll for both screens. Can anyone please help me . Its urgent.

### ISSUE THREAD

**Issue by ashishbhatia1995** [angular-split/angular-split#292]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by beeman** [comment]
@ashishbhatia1995 as suggested in another issue, the recommend way to get support is using the Discord.

Additionally, it's not at all clear what you try to achieve. You ignored the questions in the github issue. I'm going to close this issue, please don't open any new issues for the same thing.
