### ISSUE TITLE
Get initial sizes for a specific area in early lifecycle hooks

### ISSUE THREAD

**Issue by matndev** [angular-split/angular-split#293]
I use **percent to define each area** in my wrapper component with this template : 

`<as-split
            direction="horizontal"
            restrictMove="true"
            #splitTwoComponents
          >
            <as-split-area
              [size]="100 - sizes.percent.panel.myothercomponent"
              #areaMyComponent
            ><myComponent></myComponent>
            </as-split-area>
            <as-split-area><MyOtherComponent></MyOtherComponent></as-split-area>
</as-split>`

The problem is : I use `this.elementRef.nativeElement.getBoundingClientRect()` to get initial sizes in **pixels** in ngOnInit() inside MyComponent but **I get all attributes (width, height, x, y, ....) equal to zero**.

And if I use this method in ngAfterViewInit I have correct values but get ExpressionChangedAfterItHasBeenCheckedError error so it's not reliable.

How can I have initial area sizes in the child component ngOnInit or early lifecycle hooks ?

**Comment by beeman** [comment]
Hi @matndev. Thanks for creating this issue - a repro in StackBlitz would be appreciated. It should be asking for that in the issue template.

**Comment by beeman** [comment]
Please provide a StackBlitz repro.
