### ISSUE TITLE
Drop down list open behind the split area

### ISSUE THREAD

**Issue by RihabEA** [angular-split/angular-split#294]
In the as-split-area, if we have a datepicker, when we open it, it is displayed behind the split area. So to choose any date we need to resize the split area.

What we need is to open the datepicker above the split area without resizing the split area.
https://user-images.githubusercontent.com/28702053/109297376-8df4d080-783a-11eb-8f3b-08047d70dd19.PNG

**Comment by beeman** [comment]
Hi @RihabEA. Thanks for creating this issue - a repro in StackBlitz would be appreciated. It should be asking for that in the issue template.

**Comment by steflen** [comment]
got the same problem with a colorPicker from primeng [p-color / p-overlay](https://www.primefaces.org/primeng/showcase/#/colorpicker)

the problem does not occur, when using native color picker (which is fine for me)

**Comment by beeman** [comment]
Please provide a StackBlitz repro.
