### ISSUE TITLE
Splitter does not resize components as expected

### ISSUE THREAD

**Issue by vkjv** [angular-split/angular-split#304]
I am trying to understand what could block the splitter from resizing smoothly. meaning I have two split-areas which are horizontally split using the splitter layout. Each split-areas has a custom angular component which hosts an echart widget. 

Now the issue is, when I tried to drag splitter to the left, the component on the right gets expanded but the splitter handle do not move to the left but it is stuck there. The right component expands the more I drag to the left. 

If I change the direction and start moving the splitter handle to the right the left component starts expanding and the right component starts to shrink. This time the splitter handle moves.

As a next step If I start moving the splitter handle to the left, it starts moving and both the components starts to resize.
Unfortunately I could not reproduce this when tried on plunker. This is occurring only in my angular project setup and I am not able to figure what could have caused this issue to occur. 

What is different from the plunker example to my project setup is, there is ResizeService attached to the components parent element. In our case, we have a div containing echart canvas. This ResizeService listens to change in the dimension of the parent div and broadcasts the newer size object {width: x, height: y} to all the listeners. So both the components have subscribed to this service and they get the notification during the change and they resize the canvas based on the available size.

As mentioned above, when splitter is dragged to the left in the initial stage, I dont see any resize notification generated for the left most div and it does not resize. But the right one gets the notification and resizes in other direction. But I also added dragEnd event handler to the component, and it generated an event with proper sizes when dragged to the left even though the mouse did not move. 

Sorry for the big content. But any help could be useful.

**Comment by beeman** [comment]
Hey there @vkjv - thanks for submitting this issue. Could you please create a reproduction that shows the issue?

**Comment by vkjv** [comment]
Hi @beeman, unfortunately  I could not reproduce this issue with plunkr. This issue is occuring only with the project setup. And unfortunately I will not be able to share the code. 
Do you have any other suggestions?

**Comment by vkjv** [comment]
Closing the issue as I could not prepare a reproduction code.
