### ISSUE TITLE
Docs: "ui-*" classNames are wrong, should be "as-*"

### ISSUE THREAD

**Issue by lf-novelt** [angular-split/angular-split#305]
Hello, thanks for this simple and effective library

**Describe the bug**
Current version of [online documentation](https://angular-split.github.io/documentation) show **obsolete class names and components** with `ui-*` prefix that is now replaced by `as-*` 
![image](https://user-images.githubusercontent.com/46479127/128676789-bf96720b-e788-4904-9841-30457eb0993f.png)

Here is the docs source file with wrong class names and components to fix
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/src/app/documentation/documentation.component.ts#L184-L210

It has been replaced with new class names like:
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/projects/angular-split/src/lib/component/split.component.scss#L39
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/projects/angular-split/src/lib/component/split.component.scss#L10

**Comment by beeman** [comment]
Hey @lf-novelt - thanks for creating this issue. 

I would be happy to receive a PR that fixes this!

**Comment by lf-novelt** [comment]
sure, let me do that
