### ISSUE TITLE
Export Internal Interfaces 

### ISSUE THREAD

**Issue by Rajdeep97** [angular-split/angular-split#307]
**Is your feature request related to a problem? Please describe.**
Browsing the library I can see there are internal Interfaces like IOutputData, IArea, etc, please expose them so that we can refer them in our angular project.

**Describe the solution you'd like**
Please expose Internal Interfaces so that we can refer them in our angular project, eg: during the dragEnd event, we can use the type in input variable.

**Comment by beeman** [comment]
Hey @Rajdeep97 thanks for creating the issue. This should be fixed in version 13.0.1.
