### ISSUE TITLE
Support for Angular 13+

### ISSUE THREAD

**Issue by jefbarn** [angular-split/angular-split#311]
Receive the following warning on Angular 13:

Processing legacy "View Engine" libraries:
- angular-split [es2015/esm2015] (https://github.com/angular-split/angular-split.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by beeman** [comment]
Hey @jefbarn, I just published version 13.0.0 that's built with Angular 13. Please let me know if you find any issues as I'm currently not using angular-split in one of my own projects.
