### ISSUE TITLE
Spurious network call

### ISSUE THREAD

**Issue by kwood-gmr** [angular-split/angular-split#316]
Anytime there is a split area that is not resizable a single network call will be made back to the current location. Typically this will not be noticed as the web server then re-writes the call to the page origin and responds. My company is using this inside an Electron app and it results in a failed network call (that is benign, but there).

I have isolated this to the scss for the as-split component. As of writing this it is line 93. The lines affected are:
.as-split-gutter-icon {
  background-image: url('');
}

I would be glad to provide a pull request to fix this which could be done by either:

1. Replace the URL with a data url similar to the others including a single transparent pixel
2. Remove the background image

Thanks for the great package.

**Comment by beeman** [comment]
This should be fixed by #322
