### ISSUE TITLE
Resize the drag-handle

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular-split/angular-split#318]
### I would like to be able to resize the drag/resize handle. 

The default width/height of the handle is set to `11px` with this CSS style:
```
.as-split-gutter {
  flex-basis: 11px;
}
```

If I try to override this class and set the value to be something different like `7px` then a 4px (= 11 - 7) border will appear at the end of the container. It seems like some JS code is updating the `as-split-area` element size. 

It would be nice to have a clear API to resize the handle without overriding Css class, instead of via the Component's `@Input` parameter.

![image](https://user-images.githubusercontent.com/7883039/157318685-bb98006c-f96a-4461-b41e-2c3912f5cb29.png)

**Comment by beeman** [comment]
Hi @Gil-Epshtain - feel free to submit a PR that implements this.

**Comment by Gil-Epshtain** [comment]
This can be achieved via the `gutterSize` @Input parameter.
For example:
```
<as-split direction="horizontal" [gutterSize]="5">...</as-split>
