### ISSUE TITLE
Resizing in split panel when I use tinyMce component

### ISSUE THREAD

**Issue by jadsonmd** [angular-split/angular-split#321]
**Describe the issue**
If I resize a split panel with a component inside the <as-split-area> tag, in this case tinyMCE, the resizing of the area doesn't work softly.

**To Reproduce**
https://stackblitz.com/edit/angular-ivy-sedgxk?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,angular.json,src%2Fapp%2Fapp.component.html

**Comment by jadsonmd** [comment]
I solved this issue using 'Split containing iframes'.

**Solution**
https://angular-split.github.io/examples/iframes

**Comment by beeman** [comment]
Glad you found it @jadsonmd and thanks for sharing the solution for future reference!
