### ISSUE TITLE
Panels with object tags can't be resized

### ISSUE THREAD

**Issue by paulaustin-automutatio** [angular-split/angular-split#325]
**Describe the bug**
13.2.0

If you have a object tag in one of the split areas then you can't make that area smaller as the object tag consumes the pointer events so the move doesn't work.

You can fix this by setting the css style pointer-events: none when dragging on the as-split-area elements

**To Reproduce**

I tried to reproduce the simple example below, but it didn't have the same issue.

https://stackblitz.com/edit/angular-split-demo-5thfck

However setting pointer-events: none when dragging fixed it in all my more complex cases.

**Comment by Harpush** [comment]
Seems like the same problem as iframe that was fixed in #346. Closing for now.
@paulaustin-automutatio If the problem still happens with the new version 16 please open a new issue with an updated reproduction.
