### ISSUE TITLE
14.1.0 not listed as latest on npm

### ISSUE THREAD

**Issue by jefbarn** [angular-split/angular-split#328]
**Describe the bug**
Not sure if this was intentional or not, but the latest release 14.1.0 is not listed as latest on npm.

> npm info angular-split
...
dist-tags:
latest: 14.0.0  next: 14.1.0    
...

**Comment by beeman** [comment]
Thanks for letting me know, it's fixed now:

```
dist-tags:
latest: 14.1.0  next: 14.1.0
```
