### ISSUE TITLE
Add aria compliant label for gutter

### ISSUE THREAD

**Issue by CharlieGreenman** [angular-split/angular-split#347]
**Is your feature request related to a problem? Please describe.**
For the gutters, will need to add an aria-label for it to be lighthouse/a11y compliant
<img width="1126" alt="Screenshot 2023-06-25 at 8 37 27 PM" src="https://github.com/angular-split/angular-split/assets/8540141/36468f6e-9466-4725-b975-6e724b5a79c1">

**Describe the solution you'd like**
Add `aria-label="gutter width handler"` or something along those lines so that this error goes away and is a11y compliant

I am using `angular-split: "15.0.0"`

**Comment by Jefiozie** [comment]
I'm closing this issues as I believe the answer provided by @zwif is correct if not don't hesitate to reopen the issue
