### ISSUE TITLE
Buttons added either side of gutter for maximizing panes

### ISSUE THREAD

**Issue by hshahi** [angular-split/angular-split#361]
**Is your feature request related to a problem? Please describe.**
Congratulation for such an amazing component. I was wondering how easy it is to create left and right button attached to central part of the gutter where the grabber appears so that instead of dragging we can click on left arrow button ( say there is one split and 2 pane either side) then the right pane maximized and gutter goes all the way left side and then the right hand side button stay visible so that we can bring gutter back to central point. and same goes for right button, it maximized left pane.

In the central point where there is pane either side
![image](https://github.com/angular-split/angular-split/assets/10567069/69372878-c81c-4318-91a3-e47d96f2f79d)

All the way left
![image](https://github.com/angular-split/angular-split/assets/10567069/d1c1c17e-a59b-437f-9341-b05dd9000b7e)

All the way right
![image](https://github.com/angular-split/angular-split/assets/10567069/e354f970-f6c8-4481-85a8-efbd0a0279fa)

Or how easily can be implemented

Many Thanks
H

**Describe the solution you'd like**
Buttons added either side of gutter for maximizing panes

**Comment by Harpush** [comment]
Gutter customization is currently in development. Will probably allow just that using you own logic.
