### ISSUE TITLE
Transition to Angular Standalone Components in Favor of Angular Modules

### ISSUE THREAD

**Issue by Jefiozie** [angular-split/angular-split#378]
To align with modern Angular development practices, we propose migrating our project to use Angular Standalone Components. This transition aims to simplify our application architecture, improve modularity, and enhance developer experience.

**Comment by Harpush** [comment]
As a non breaking change first phase - we can transition to standalone but remain with an exported module importing and re-exporting the standalone components/directives.

One other concern is we currently have multiple directives and components that are needed for the split to function. How will end users import those in a "bundle"? If I remember correctly exporting a const array still doesn't work from libraries.

**Comment by Jefiozie** [comment]
I agree on the fact that we can easily do both for the current version. And when we bump to a major version remove the module.

About the question, yes there is a problem with the import of standalone CMP /directives with an array. But there is also a workaround, we can use the spread operator to still import them. There is an ongoing issue that will fix the array without a spread operator.

**Comment by Harpush** [comment]
Just adding that we should introduce `provideAngularSplit` or `provideAngularSplitOptions` to allow using `ANGULAR_SPLIT_DEFAULT_OPTIONS` easier.
