### ISSUE TITLE
First time installation on windows fails due to nx

### ISSUE THREAD

**Issue by Harpush** [angular-split/angular-split#435]
When trying `npm i` on an empty project (no node_modules) on a windows machine using node v20.11.0 the installation fails with:
Error: Cannot find module '@nx/nx-win32-x64-msvc'

**Comment by Harpush** [comment]
@SanderElias This is the issue concerning what we spoke about

**Comment by Jefiozie** [comment]
So, I've found out that it is comming from the `angular-eslint` package, specificly the builder. It has a dependency on NX which may or may not is needed there. WE are checking with the author it this is correct or not. 
The workaround in the mean time is to remove the package-lock file. Then NPM will install all packages that are needed for the OS. In the package-lock file is a reference to a LINUX part of nx where this is not working for windows.

**Comment by Jefiozie** [comment]
Closing this as we made a fix for it
