### ISSUE TITLE
min size of first area with only 2 areas

### ISSUE THREAD

**Issue by ranitg** [angular-split/angular-split#439]
**Describe the bug**
When only having 2 split areas (with pixel units), the minSize for the first area does not work. Only the second area works with minimum size.

**To Reproduce**
https://stackblitz.com/edit/angular-split-demo-utckr3?file=src%2Fapp%2Fapp.component.html

**Comment by Harpush** [comment]
Confirmed. Will look at it later. An upcoming refactor solves it anyway.

**Comment by ranitg** [comment]
When do you think this will be available?
