### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by getcovered-olivier** [angular-split/angular-split#445]
**Describe the bug**

I love your library (which I've used on much older Angular versions) but I'm still on Angular 13 at work. Is there a NPM version I can refer to for it?
I checked package.json of the tags and it says 0.0.0.

Thanks

**To Reproduce**
Create a Stackblitz demoing the bug/issue:
https://stackblitz.com/

**Comment by ccondrup** [comment]
It seems the versioning for this project is matching Angular on major version, so you should be able to use 13.x.x
When I entered 13 and autocompleted in my IDE now, it listed 13.2.0 as the most recent. Give it a try.

```
// package.json
"dependencies": { 
  "angular-split": "13.2.0",
}
```

**Comment by getcovered-olivier** [comment]
Seems to do it.Thanks
