### ISSUE TITLE
Console message "maxSize/minSize not allowed on *" in latest beta

### ISSUE THREAD

**Issue by elementalTIMING** [angular-split/angular-split#448]
Hi,

the v18 beta this message is shown in the console.

      maxSize/minSize not allowed on * or without size

My config, that I used since years, looks like:

	/** some default split area values */
	public splitSizes = {
		left: {
			default: 350,
			current: 350,
			min: 290,
			max: 600,
		},
		right: {
			default: '*',
			current: '*',
			min: 500,
			max: '*',
		},
	};

The code still seems to work properly. But how to change it to let the warning disappear? Is it an issue of the latest beta or something that is not documented yet (or that I haven't found in the docs)?

Thx for a response and/or a fix.

**Comment by Harpush** [comment]
Hey
You right area is declared as * but has a minimum of 500.
Did that minimum ever worked for you?

**Comment by elementalTIMING** [comment]
> Hey You right area is declared as * but has a minimum of 500. Did that minimum ever worked for you?

so far it works like a charm and I never discovered any issues.

**Comment by Harpush** [comment]
> > Hey You right area is declared as * but has a minimum of 500. Did that minimum ever worked for you?
> 
> so far it works like a charm and I never discovered any issues.

I mean did the minimum 500 worked before the beta? The console warn is because it won't work and invalid. I just want to make sure we didn't break anything here

**Comment by elementalTIMING** [comment]
> > > Hey You right area is declared as * but has a minimum of 500. Did that minimum ever worked for you?
> > 
> > 
> > so far it works like a charm and I never discovered any issues.
> 
> I mean did the minimum 500 worked before the beta? The console warn is because it won't work and invalid. I just want to make sure we didn't break anything here

I really guess that it worked. I have here an app for desktop and mobiles. Sometimes I hide the left section in the code and then the right section takes the size but not smaller than 500

**Comment by elementalTIMING** [comment]
> Can you please check and compare the minimum size behavior from before the beta compared to the beta? I suspect it never worked as expected but let's make sure

I'll test it tomorrow and will give you a feedback

**Comment by Jefiozie** [comment]
Hi @elementalTIMING did you have any feedback for us ? Thanks in advance

**Comment by elementalTIMING** [comment]
> Hi @elementalTIMING did you have any feedback for us ? Thanks in advance

oh sorry, I completely forgot to test

**Comment by Harpush** [comment]
@elementalTIMING Did you check by any chance?

**Comment by Harpush** [comment]
Due to no answer closing this issue. Please open a new one if needed.
