### ISSUE TITLE
18.0.0-beta.0 breaks resizing with mouse via gutters on Firefox

### ISSUE THREAD

**Issue by davidfiala** [angular-split/angular-split#454]
**Describe the bug**

Bug exists in: `18.0.0-beta.0` using Firefox `129.0.2 (64-bit)` (latest as of writing)
But does not exist in `17.1.1` using otherwise same code and configuration.

**To Reproduce**

Upon moving mouse and clicking to drag a gutter, nothing happens and console logs:

```
Uncaught ReferenceError: TouchEvent is not defined
    Angular 3
        getPointFromEvent
        gutterEventsEqualWithDelta
        _SplitCustomEventsBehaviorDirective/dragStarted$</<
    RxJS 2
        filter
        _next
```

Basic example:

```
    <as-split direction="vertical">
      <as-split-area size="80">
        <h1>bar</h1>
      </as-split-area>
      <as-split-area size="20">
        <h1>foo</h1>
      </as-split-area>
    </as-split>
 ```

**Comment by Harpush** [comment]
Known issue - there is already a PR for fixing it
