### ISSUE TITLE
No support for Arabic

### ISSUE THREAD

**Issue by niranjan1988** [angular-split/angular-split#461]
When we change the document dir to 'rtl', the  panels move to right  but the panels are not rearranged from right to left which is expected for arabic language

Issue can be seen here 
https://stackblitz.com/edit/angular-split-demo-dhdffm?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by Harpush** [comment]
Have you tried using the split component input `dir`? Should fix your issue

**Comment by niranjan1988** [comment]
It worked. Thanks a lot
