### ISSUE TITLE
Angular 19 update

### ISSUE THREAD

**Issue by eamon-otuathail** [angular-split/angular-split#463]
Angular 19 (RC) has arrived:
  https://github.com/angular/angular/blob/main/CHANGELOG.md
and the v19 full release is expected very soon.

Are there plans for a v19 release of Angular-Split; and if so, is there an ETA of its release.
If possible, I would like to use it for a new project I am planning.

**Comment by Jefiozie** [comment]
Yes we will support v19 at some point. We don't have any estimations atm. We are working on finalizing the v18 transition.
