### ISSUE TITLE
Exported SplitAreaDirective no longer exported (as of v18)

### ISSUE THREAD

**Issue by whernebrink** [angular-split/angular-split#468]
**Describe the bug**
We''ve been using the previously exported `SplitAreaDirective` like this:
![image](https://github.com/user-attachments/assets/157d08ec-0319-4f74-8e2e-b9cee07560fa)

But since of latests refactor, the directive is no longer exported. Is there any reason for it not to be exported anymore? 
Would be nice if it was.. 

**To Reproduce**
- Try importing `SplitAreaDirective` in v17 vs v18.

**Comment by Harpush** [comment]
The `SplitAreaDirective` is now `SplitAreaComponent`
