### ISSUE TITLE
Several bugs in documentation

### ISSUE THREAD

**Issue by jeandat** [angular-split/angular-split#469]
**Describe the bug**

Documentation site has several bugs:

- in top right corner, github logo does not appear (see capture below)
- on [collapse/expand](https://angular-split.github.io/examples/collapse-expand) page, demo is broken, nothing happens when clicking the buttons
- on [API](https://angular-split.github.io/documentation) page, `SplitAreaDirective` should be `SplitAreaComponent`

Logo capture:
![Screenshot 2024-11-15 at 15 12 46](https://github.com/user-attachments/assets/95e954ef-443d-4a26-95b1-3c9ee33207c4)

**Comment by Harpush** [comment]
@jeandat Expand/Collapse feature was removed in v18. We are planning a replacement that better fits a split component.
You can see the RFC here: https://github.com/angular-split/angular-split/discussions/458
